"use strict";
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//egy mondat NEM STOP szavainak rendezett sorrendben való kiírása
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//magyar stop szavak:
const hu_stop = {
  a: true,
  ahogy: true,
  ahol: true,
  aki: true,
  akik: true,
  akkor: true,
  alatt: true,
  által: true,
  általában: true,
  amely: true,
  amelyek: true,
  amelyekben: true,
  amelyeket: true,
  amelyet: true,
  amelynek: true,
  ami: true,
  amit: true,
  amolyan: true,
  amíg: true,
  amikor: true,
  át: true,
  abban: true,
  ahhoz: true,
  annak: true,
  arra: true,
  arról: true,
  az: true,
  azok: true,
  azon: true,
  azt: true,
  azzal: true,
  azért: true,
  aztán: true,
  azután: true,
  azonban: true,
  bár: true,
  be: true,
  belül: true,
  benne: true,
  cikk: true,
  cikkek: true,
  cikkeket: true,
  csak: true,
  de: true,
  e: true,
  eddig: true,
  egész: true,
  egy: true,
  egyes: true,
  egyetlen: true,
  egyéb: true,
  egyik: true,
  egyre: true,
  ekkor: true,
  el: true,
  elég: true,
  ellen: true,
  elő: true,
  először: true,
  előtt: true,
  első: true,
  én: true,
  éppen: true,
  ebben: true,
  ehhez: true,
  emilyen: true,
  ennek: true,
  erre: true,
  ez: true,
  ezt: true,
  ezek: true,
  ezen: true,
  ezzel: true,
  ezért: true,
  és: true,
  fel: true,
  felé: true,
  ha: true,
  hanem: true,
  hiszen: true,
  hogy: true,
  hogyan: true,
  igen: true,
  így: true,
  illetve: true,
  "ill.": true,
  ill: true,
  ilyen: true,
  ilyenkor: true,
  ison: true,
  ismét: true,
  itt: true,
  jó: true,
  jól: true,
  jobban: true,
  kell: true,
  kellett: true,
  keresztül: true,
  keressünk: true,
  ki: true,
  kívül: true,
  között: true,
  közül: true,
  legalább: true,
  lehet: true,
  lehetett: true,
  legyen: true,
  lenne: true,
  lenni: true,
  lesz: true,
  lett: true,
  maga: true,
  magát: true,
  majd: true,
  majd: true,
  már: true,
  más: true,
  másik: true,
  meg: true,
  még: true,
  mellett: true,
  mert: true,
  mely: true,
  melyek: true,
  mi: true,
  mit: true,
  míg: true,
  miért: true,
  milyen: true,
  mikor: true,
  minden: true,
  mindent: true,
  mindenki: true,
  mindig: true,
  mint: true,
  mintha: true,
  mivel: true,
  most: true,
  nagy: true,
  nagyobb: true,
  nagyon: true,
  ne: true,
  néha: true,
  nekem: true,
  neki: true,
  nem: true,
  néhány: true,
  nélkül: true,
  nincs: true,
  olyan: true,
  ott: true,
  össze: true,
  ő: true,
  ők: true,
  őket: true,
  pedig: true,
  persze: true,
  rá: true,
  is: true,
  saját: true,
  sem: true,
  semmi: true,
  sok: true,
  sokat: true,
  sokkal: true,
  számára: true,
  szemben: true,
  szerint: true,
  szinte: true,
  talán: true,
  tehát: true,
  teljes: true,
  tovább: true,
  továbbá: true,
  több: true,
  úgy: true,
  ugyanis: true,
  új: true,
  újabb: true,
  újra: true,
  után: true,
  utána: true,
  utolsó: true,
  vagy: true,
  vagyis: true,
  valaki: true,
  valami: true,
  valamint: true,
  való: true,
  vagyok: true,
  van: true,
  vannak: true,
  volt: true,
  voltam: true,
  voltak: true,
  voltunk: true,
  vissza: true,
  vele: true,
  viszont: true,
  volna: true,
};

//mondat:
let mo =
  "Nyugodtan rohanunk a szakadékba is, ha sikerült valamivel eltakarnunk a szemünk elől.";

console.log('Szöveg: "' + mo + '"');

mo = mo.toLocaleLowerCase("hu-HU"); //lokális kisbetűsre

let szavak = mo.split(/[\s.,;:!?]+/); //felbontom az elválasztók és írásjelek szerint

szavak.sort((s1, s2) => s1.localeCompare(s2, "hu-HU")); //rendezve sztring szerint, a tömb módosul

console.log("Szavak rendezve:" + szavak);

let lista = szavak.filter((szo) => !hu_stop[szo]); //új tömböt állít elő azokra a szavakra amelyek nem stop szavak

console.log("Nem stop szavak sorrendben:");

lista.forEach((szo) => console.log(szo));
